version: "3.9"

services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  backend:
    build: ./app
    container_name: diary_app
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "
        cd /app &&
        sleep 20 &&
        alembic -c alembic.ini upgrade head &&
        uvicorn main:app --host 0.0.0.0 --port 8000
      "

volumes:
  postgres_data:
